version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - sphinx-apidoc -f -o docs/source/api mars --separate -M
      # Fix escaped underscores
      - python docs/fix_rst.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - opt
        - plot
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false