version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Clean old generated files
      - rm -rf docs/source/api
      # Regenerate API docs with proper options
      - sphinx-apidoc -f -o docs/source/api mars --separate --module-first --no-toc
      # Fix RST files
      - python docs/fix_rst.py
      # Debug: show what was generated
      - echo "=== Generated RST files ==="
      - find docs/source/api -name "*.rst" -type f | head -20

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - opt
        - plot
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false