#!/usr/bin/env python3
"""Fix escaped underscores and improve RST files generated by sphinx-apidoc."""

import re
from pathlib import Path

def fix_rst_file(filepath):
    """Fix common issues in sphinx-apidoc generated RST files."""
    content = filepath.read_text(encoding='utf-8')
    original_content = content
    
    # Fix 1: Remove backslash escapes from automodule/autoclass/autofunction directives
    content = re.sub(
        r'(\.\. auto(?:module|class|function|method|attribute):: )([^\n]*)',
        lambda m: m.group(1) + m.group(2).replace('\\_', '_'),
        content
    )
    
    # Fix 2: Ensure :members: is present for all automodule directives
    # Find automodule blocks and ensure they have proper options
    def ensure_members(match):
        directive = match.group(0)
        indent = match.group(1)
        
        # Check if already has options
        if ':members:' not in directive:
            # Add standard options
            options = f"\n{indent}   :members:\n{indent}   :undoc-members:\n{indent}   :show-inheritance:"
            # Insert after the directive line
            lines = directive.split('\n')
            lines.insert(1, options)
            return '\n'.join(lines)
        return directive
    
    content = re.sub(
        r'^(\s*)\.\. automodule:: ([^\n]+)(?:\n(?:\1   :[^\n]+)?)*',
        ensure_members,
        content,
        flags=re.MULTILINE
    )
    
    # Fix 3: For package index files, ensure submodules are included
    if filepath.name.endswith('.rst') and 'Subpackages' in content:
        # This is a package index, make sure it includes submodules properly
        pass  # sphinx-apidoc should handle this
    
    if content != original_content:
        filepath.write_text(content, encoding='utf-8')
        print(f"Fixed: {filepath.relative_to(filepath.parents[2])}")
        return True
    return False

def main():
    """Process all RST files in the API directory."""
    script_dir = Path(__file__).parent
    api_dir = script_dir / 'source' / 'api'
    
    if not api_dir.exists():
        print(f"API directory not found: {api_dir}")
        print("Run sphinx-apidoc first!")
        return 1
    
    print("Fixing RST files in", api_dir)
    fixed_count = 0
    
    for rst_file in api_dir.rglob('*.rst'):
        if fix_rst_file(rst_file):
            fixed_count += 1
    
    print(f"\nProcessed files, fixed {fixed_count} files")
    return 0

if __name__ == '__main__':
    exit(main())